micronaut:
  server:
    port: 8081
  http.services:
    pet-health:
      urls: "http://localhost:8082"
  application:
    name: exampleAtp
  http:
    services:
      pet-health:
        url: http://localhost:8082
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa 
    schema-generate: CREATE_DROP
#    dialect: Oracle

#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create
#        show_sql: true