micronaut:
  http.services:
    pet-health:
      urls: "http://localhost:8081"
  application:
    name: exampleAtp
  http:
    services:
      pet-health:
        url: http://localhost:8081
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

